package com.github.bandithelps.abilities;

import com.github.bandithelps.YourHeroAcademia;
import com.github.bandithelps.abilities.blockdisplayanims.BDBodyPartEmitterAbility;
import com.github.bandithelps.abilities.blockdisplayanims.BDDomeAbility;
import com.github.bandithelps.abilities.blockdisplayanims.BDShockwaveAbility;
import com.github.bandithelps.abilities.blockdisplayanims.BDTrailAbility;
import com.github.bandithelps.abilities.bodydata.DisplayBodyBarAbility;
import com.github.bandithelps.abilities.bodydata.BodyPartValueTickAbility;
import com.github.bandithelps.abilities.bodydata.DamageBodyPartAbility;
import com.github.bandithelps.abilities.bodydata.HealBodyPartAbility;
import com.github.bandithelps.abilities.bodydata.SetBodyStringAbility;
import com.github.bandithelps.abilities.blackwhip.BlackwhipAoeTagAbility;
import com.github.bandithelps.abilities.blackwhip.BlackwhipAuraAbility;
import com.github.bandithelps.abilities.blackwhip.BlackwhipBlockGrabAbility;
import com.github.bandithelps.abilities.blackwhip.BlackwhipBubbleShieldAbility;
import com.github.bandithelps.abilities.blackwhip.BlackwhipDetachAbility;
import com.github.bandithelps.abilities.blackwhip.BlackwhipLashAbility;
import com.github.bandithelps.abilities.blackwhip.BlackwhipMoveTaggedAbility;
import com.github.bandithelps.abilities.blackwhip.BlackwhipQuadZipAbility;
import com.github.bandithelps.abilities.blackwhip.BlackwhipRestrainAbility;
import com.github.bandithelps.abilities.blackwhip.BlackwhipRestrictAbility;
import com.github.bandithelps.abilities.blackwhip.BlackwhipTagAbility;
import com.github.bandithelps.abilities.blackwhip.BlackwhipYankAbility;
import com.github.bandithelps.abilities.blackwhip.BlackwhipZipAbility;
import com.github.bandithelps.abilities.blackwhip.chain.BlackwhipChainChargeZipAbility;
import com.github.bandithelps.abilities.blackwhip.chain.BlackwhipChainDetachAbility;
import com.github.bandithelps.abilities.blackwhip.chain.BlackwhipChainSwingAbility;
import com.github.bandithelps.abilities.blackwhip.chain.BlackwhipChainTagAbility;
import com.github.bandithelps.abilities.blackwhip.chain.BlackwhipChainZipAbility;
import com.github.bandithelps.abilities.decay.DecayFistAbility;
import com.github.bandithelps.abilities.decay.DecayInstabilityAbility;
import com.github.bandithelps.abilities.decay.EnvironmentDecayAbility;
import com.github.bandithelps.abilities.decay.RotAbility;
import com.github.bandithelps.abilities.common.PlaySoundAbility;
import com.github.bandithelps.abilities.common.PotionGeneratorAbility;
import com.github.bandithelps.abilities.common.SmokeCanisterChargeAbility;
import com.github.bandithelps.abilities.common.SprayAttackAbility;
import com.github.bandithelps.abilities.movement.DashAbility;
import net.neoforged.neoforge.registries.DeferredHolder;
import net.neoforged.neoforge.registries.DeferredRegister;
import net.threetag.palladium.power.ability.AbilitySerializer;
import net.threetag.palladium.registry.PalladiumRegistryKeys;

public class AbilityRegister {

    public static final DeferredRegister<AbilitySerializer<?>> ABILITIES;
    public static final DeferredHolder<AbilitySerializer<?>, DashAbility.Serializer> DASH;
    public static final DeferredHolder<AbilitySerializer<?>, DamageBodyPartAbility.Serializer> DAMAGE_BODY_PART;
    public static final DeferredHolder<AbilitySerializer<?>, HealBodyPartAbility.Serializer> HEAL_BODY_PART;
    public static final DeferredHolder<AbilitySerializer<?>, BodyPartValueTickAbility.Serializer> CHANGE_BODY_VALUE;
    public static final DeferredHolder<AbilitySerializer<?>, DisplayBodyBarAbility.Serializer> DISPLAY_BODY_BAR;
    public static final DeferredHolder<AbilitySerializer<?>, BDShockwaveAbility.Serializer> BD_SHOCKWAVE;
    public static final DeferredHolder<AbilitySerializer<?>, BDDomeAbility.Serializer> BD_DOME;
    public static final DeferredHolder<AbilitySerializer<?>, BDBodyPartEmitterAbility.Serializer> BD_BODY_PART_EMITTER;
    public static final DeferredHolder<AbilitySerializer<?>, BDTrailAbility.Serializer> BD_TRAIL;
    public static final DeferredHolder<AbilitySerializer<?>, PotionGeneratorAbility.Serializer> POTION_GEN;
    public static final DeferredHolder<AbilitySerializer<?>, SprayAttackAbility.Serializer> SPRAY_ATTACK;
    public static final DeferredHolder<AbilitySerializer<?>, PlaySoundAbility.Serializer> PLAY_SOUND;
    public static final DeferredHolder<AbilitySerializer<?>, SmokeCanisterChargeAbility.Serializer> SMOKE_CANISTER_CHARGE;
    public static final DeferredHolder<AbilitySerializer<?>, SetBodyStringAbility.Serializer> SET_BODY_STRING;
    public static final DeferredHolder<AbilitySerializer<?>, DecayFistAbility.Serializer> DECAY_FIST;
    public static final DeferredHolder<AbilitySerializer<?>, EnvironmentDecayAbility.Serializer> ENVIRONMENT_DECAY;
    public static final DeferredHolder<AbilitySerializer<?>, RotAbility.Serializer> ROT_WAVE;
    public static final DeferredHolder<AbilitySerializer<?>, DecayInstabilityAbility.Serializer> DECAY_INSTABILITY;
    public static final DeferredHolder<AbilitySerializer<?>, BlackwhipTagAbility.Serializer> BLACKWHIP_TAG;
    public static final DeferredHolder<AbilitySerializer<?>, BlackwhipAoeTagAbility.Serializer> BLACKWHIP_AOE_TAG;
    public static final DeferredHolder<AbilitySerializer<?>, BlackwhipDetachAbility.Serializer> BLACKWHIP_DETACH;
    public static final DeferredHolder<AbilitySerializer<?>, BlackwhipRestrictAbility.Serializer> BLACKWHIP_RESTRICT;
    public static final DeferredHolder<AbilitySerializer<?>, BlackwhipMoveTaggedAbility.Serializer> BLACKWHIP_MOVE_TAGGED;
    public static final DeferredHolder<AbilitySerializer<?>, BlackwhipRestrainAbility.Serializer> BLACKWHIP_RESTRAIN;
    public static final DeferredHolder<AbilitySerializer<?>, BlackwhipZipAbility.Serializer> BLACKWHIP_ZIP;
    public static final DeferredHolder<AbilitySerializer<?>, BlackwhipQuadZipAbility.Serializer> BLACKWHIP_QUAD_ZIP;
    public static final DeferredHolder<AbilitySerializer<?>, BlackwhipAuraAbility.Serializer> BLACKWHIP_AURA;
    public static final DeferredHolder<AbilitySerializer<?>, BlackwhipBubbleShieldAbility.Serializer> BLACKWHIP_BUBBLE_SHIELD;
    public static final DeferredHolder<AbilitySerializer<?>, BlackwhipBlockGrabAbility.Serializer> BLACKWHIP_BLOCK_GRAB;
    public static final DeferredHolder<AbilitySerializer<?>, BlackwhipLashAbility.Serializer> BLACKWHIP_LASH;
    public static final DeferredHolder<AbilitySerializer<?>, BlackwhipYankAbility.Serializer> BLACKWHIP_YANK;
    public static final DeferredHolder<AbilitySerializer<?>, BlackwhipChainTagAbility.Serializer> BLACKWHIP_CHAIN_TAG;
    public static final DeferredHolder<AbilitySerializer<?>, BlackwhipChainDetachAbility.Serializer> BLACKWHIP_CHAIN_DETACH;
    public static final DeferredHolder<AbilitySerializer<?>, BlackwhipChainSwingAbility.Serializer> BLACKWHIP_CHAIN_SWING;
    public static final DeferredHolder<AbilitySerializer<?>, BlackwhipChainZipAbility.Serializer> BLACKWHIP_CHAIN_ZIP;
    public static final DeferredHolder<AbilitySerializer<?>, BlackwhipChainChargeZipAbility.Serializer> BLACKWHIP_CHAIN_CHARGE_ZIP;

    static {
        ABILITIES = DeferredRegister.create(PalladiumRegistryKeys.ABILITY_SERIALIZER, YourHeroAcademia.MODID);
        DASH = ABILITIES.register("dash", DashAbility.Serializer::new);
        DAMAGE_BODY_PART = ABILITIES.register("damage_body_part", DamageBodyPartAbility.Serializer::new);
        HEAL_BODY_PART = ABILITIES.register("heal_body_part", HealBodyPartAbility.Serializer::new);
        CHANGE_BODY_VALUE = ABILITIES.register("change_body_value", BodyPartValueTickAbility.Serializer::new);
        DISPLAY_BODY_BAR = ABILITIES.register("display_body_bar", DisplayBodyBarAbility.Serializer::new);
        BD_SHOCKWAVE = ABILITIES.register("bd_shockwave", BDShockwaveAbility.Serializer::new);
        BD_DOME = ABILITIES.register("bd_dome", BDDomeAbility.Serializer::new);
        BD_BODY_PART_EMITTER = ABILITIES.register("bd_body_part_emitter", BDBodyPartEmitterAbility.Serializer::new);
        BD_TRAIL = ABILITIES.register("bd_trail", BDTrailAbility.Serializer::new);
        POTION_GEN = ABILITIES.register("potion_gen", PotionGeneratorAbility.Serializer::new);
        SPRAY_ATTACK = ABILITIES.register("spray_attack", SprayAttackAbility.Serializer::new);
        PLAY_SOUND = ABILITIES.register("play_sound", PlaySoundAbility.Serializer::new);
        SMOKE_CANISTER_CHARGE = ABILITIES.register("smoke_canister_charge", SmokeCanisterChargeAbility.Serializer::new);
        SET_BODY_STRING = ABILITIES.register("set_body_string", SetBodyStringAbility.Serializer::new);
        DECAY_FIST = ABILITIES.register("decay_fist", DecayFistAbility.Serializer::new);
        ENVIRONMENT_DECAY = ABILITIES.register("environment_decay", EnvironmentDecayAbility.Serializer::new);
        ROT_WAVE = ABILITIES.register("rot_wave", RotAbility.Serializer::new);
        DECAY_INSTABILITY = ABILITIES.register("decay_instability", DecayInstabilityAbility.Serializer::new);
        BLACKWHIP_TAG = ABILITIES.register("blackwhip_tag", BlackwhipTagAbility.Serializer::new);
        BLACKWHIP_AOE_TAG = ABILITIES.register("blackwhip_aoe_tag", BlackwhipAoeTagAbility.Serializer::new);
        BLACKWHIP_DETACH = ABILITIES.register("blackwhip_detach", BlackwhipDetachAbility.Serializer::new);
        BLACKWHIP_RESTRICT = ABILITIES.register("blackwhip_restrict", BlackwhipRestrictAbility.Serializer::new);
        BLACKWHIP_MOVE_TAGGED = ABILITIES.register("blackwhip_move_tagged", BlackwhipMoveTaggedAbility.Serializer::new);
        BLACKWHIP_RESTRAIN = ABILITIES.register("blackwhip_restrain", BlackwhipRestrainAbility.Serializer::new);
        BLACKWHIP_ZIP = ABILITIES.register("blackwhip_zip", BlackwhipZipAbility.Serializer::new);
        BLACKWHIP_QUAD_ZIP = ABILITIES.register("blackwhip_quad_zip", BlackwhipQuadZipAbility.Serializer::new);
        BLACKWHIP_AURA = ABILITIES.register("blackwhip_aura", BlackwhipAuraAbility.Serializer::new);
        BLACKWHIP_BUBBLE_SHIELD = ABILITIES.register("blackwhip_bubble_shield", BlackwhipBubbleShieldAbility.Serializer::new);
        BLACKWHIP_BLOCK_GRAB = ABILITIES.register("blackwhip_block_grab", BlackwhipBlockGrabAbility.Serializer::new);
        BLACKWHIP_LASH = ABILITIES.register("blackwhip_lash", BlackwhipLashAbility.Serializer::new);
        BLACKWHIP_YANK = ABILITIES.register("blackwhip_yank", BlackwhipYankAbility.Serializer::new);
        BLACKWHIP_CHAIN_TAG = ABILITIES.register("blackwhip_chain_tag", BlackwhipChainTagAbility.Serializer::new);
        BLACKWHIP_CHAIN_DETACH = ABILITIES.register("blackwhip_chain_detach", BlackwhipChainDetachAbility.Serializer::new);
        BLACKWHIP_CHAIN_SWING = ABILITIES.register("blackwhip_chain_swing", BlackwhipChainSwingAbility.Serializer::new);
        BLACKWHIP_CHAIN_ZIP = ABILITIES.register("blackwhip_chain_zip", BlackwhipChainZipAbility.Serializer::new);
        BLACKWHIP_CHAIN_CHARGE_ZIP = ABILITIES.register("blackwhip_chain_charge_zip", BlackwhipChainChargeZipAbility.Serializer::new);
    }

}
